server:
  port: 8080

logging:
  level:
    ROOT: INFO
    az.baxtiyargil.employeemanagementws: DEBUG

spring:
  application:
    name: employee-management-ws
  liquibase:
    change-log: classpath:config/liquibase/changelog-master.xml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:employee;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: employee
    password:
    hikari:
      poolName: EmployeeHikariPool
      auto-commit: false
  h2:
    console:
      enabled: true
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false

application:
  swagger:
    base-package: "az.baxtiyargil.employeemanagementws"
    paths: "/.*"